sudo: required
dist: trusty

language: php
php:
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

install:
  - sh -c "sudo apt-get -y install uuid-dev libgearman-dev gearman gearman-job-server"
before_script:
  - curl -L -o gearman-0.8.3.tgz http://pecl.php.net/get/gearman/0.8.3
  - tar -xzf gearman-0.8.3.tgz
  - sh -c "cd gearman-0.8.3 && phpize && ./configure && make && sudo make install && cd .."
  - echo "extension=gearman.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --prefer-source --no-interaction

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    email: false
